[package]
authors = ["Sam Denty <sam@samdenty.com>"]
edition = "2018"
name = "repositories"
version = "0.1.0"

[dependencies]
byteorder = "1.3.4"
colored = "2"
failure = "0.1.8"
fuse = {git = "https://github.com/zargony/fuse-rs"}
github-rs = "0.7.0"
headless_chrome = {version = "0.9.0"}
hex-literal = "0.3.1"
icns = "0.3.1"
libc = "0.2.51"
once_cell = "1.5.2"
parking_lot = "0.11.1"
reqwest = {version = "0.10", features = ["json"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tokio = {version = "0.2", features = ["full"]}

[dev-dependencies]
env_logger = "0.6.0"
