# [tasks.watch]
# # env = { "CARGO_MAKE_MEMBER_TASK" = "echo", "CARGO_MAKE_WORKSPACE_SKIP_MEMBERS" = "member2" }
# run_task = "watch"

# [tasks.echo]
# env = { "ECHO_TEST" = "ECHO_ENV" }
# script = '''
# echo watch triggered
# echo ECHO_TEST: ${ECHO_TEST}
# echo CARGO_MAKE_DISABLE_WATCH: ${CARGO_MAKE_DISABLE_WATCH}
# '''
# watch = true
